name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  client:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.1"

      - name: build client container
        run: docker-compose up --no-start client

      - name: install dependencies
        run: |
          cd client/
          yarn
      - name: run client tests
        run: docker-compose run client yarn run test:unit

      - name: sonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: deploy
        uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gces-app" #Must be unique in Heroku
          heroku_email: "esio.gustavo@gmail.com"
          usedocker: true

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build api containers
        run: docker-compose up --no-start api

      - name: create database
        run: docker-compose run api rake db:create

      - name: create migrations
        run: docker-compose run api rake db:migrate

      - name: run api tests
        run: docker-compose run api bundle exec rails test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: deploy
        uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gces-api" #Must be unique in Heroku
          heroku_email: "esio.gustavo@gmail.com"
          usedocker: true
