name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  client:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.15.1'

    - name: build client container
      run: docker-compose up --no-start client

    - name: install dependencies
      run: |
        cd client/
        yarn
    - name: run client tests
      run:  docker-compose run client yarn run test:unit
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: 7a8845ad0dc6e0158ef08fc1e103d77e878fb513853746ad40b62a7e2bb8cc74


  api:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: build api containers
          run:  docker-compose up --no-start api

        - name: create database
          run:  docker-compose run api rake db:create

        - name: create migrations
          run:  docker-compose run api rake db:migrate

        - name: run api tests
          run : docker-compose run api bundle exec rails test

        - name: Code Climate Coverage Action
          uses: paambaati/codeclimate-action@v2.7.4

